### ISSUE TITLE
[Bug]: Local analyzis with CLI not working

### ISSUE THREAD

**Issue by vvatelot** [cnumr/EcoIndex_python#38]
### What happened?

When trying to analyze a loclahost page, it fails when using docker.

Should declare host network configuration in readme

### Project

Ecoindex CLI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PaulPHPE** [comment]
Inside the docker container, "localhost" is the container itself, and it is not the host's "localhost". We need to explicitly tell docker to get the machine host.   

On Linux, you can pass network configuration to the docker run command  `--network host` and it should work
But according to the docker documentation : "The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server."


On Mac and Windows we need to use "host.docker.internal". For example, if you want to analyse : http://localhost:4321, you should write : 
ecoindex-cli analyze --url http://host.docker.internal:4321/

The problem with this solution is that the —recursive flag won’t work. 
My proposition is to filter the URLs in the scrap_page function, and replace all localhost occurrences with host.docker.internal. We could maybe add a flag --local-mac or --local-windows to trigger the filter

@vvatelot what do you think ? 


PS: There might be other solutions that I don't know of.

**Comment by vvatelot** [comment]
Hello @PaulPHPE Thank you very much for your analysis!
So, if I try to make a summary:
- On linux, just need to update the readme so that the alias we create contains `--network host` in it, right ?
- On Windows and Mac, not possible and to target `localhost` analysis we have to use `host.docker.internal`, right ? So, in this case you propose to replace the `localhost` url with `host.docker.internal` in the CLI app itself...

2 questions here:
- Can we use the same logic for linux, mac and windows ? :thinking: 
- Instead adding a new param based on user's platform, shouldn't it be better to add an environment variable in the docker container, and make modification inside the app based on this variable? (if the env var is set, we know that we are running adocker container...)

What do you think ?

**Comment by PaulPHPE** [comment]
Hello @vvatelot ! 

Thank you for the summary ! Yes and yes for the two points.   

For the questions : 

* Yes we could use the same logic for all platforms. We can use `host.docker.internal` on linux. But this would require to add the flag `--add-host=host.docker.internal:host-gateway` to the docker run command for linux.
* Yes this could be better indeed. 


If we use `host.docker.internal` method for all platforms, we do not need to add a variable. The solution would then be : 
1/ update the README to add `--add-host=host.docker.internal:host-gateway` for linux users
2/ replace the `localhost` url with `host.docker.internal` in the CLI app itself (I am still trying to figure out how to make this work with the scrappy crawler, i will propose a PR once I make it work)
