### ISSUE TITLE
Aide - lancement de ecoindex_cli dans ce projet global

### ISSUE THREAD

**Issue by xadag-yogarik** [cnumr/EcoIndex_python#79]
Bonjour,

Je ne suis pas familier avec les tasks de poetry et je n'ai pas trouvé comment lancer comme sur le repo autonome https://github.com/cnumr/ecoindex_cli le client ecoindex_cli pour mes analyzes.

J'ai essayé

`ubuntu@xxxx:~/ecoindex_python_fullstack/projects/ecoindex_cli$ task docker-build
Updating dependencies
Resolving dependencies... (5.1s)

The command "build-project" does not exist.
exit status 1
ubuntu@xxxx:~/ecoindex_python_fullstack/projects/ecoindex_cli$ `

Sans trop de succès.
Pourriez-vous m'aider.

Merci !

**Comment by vvatelot** [comment]
Bonjour @xadag-yogarik, normalement si tu suis la [documentation](https://github.com/cnumr/ecoindex_python_fullstack/blob/main/projects/ecoindex_cli/README.md#quickstart) tu dois pouvoir lancer une analyse en utilisant docker.

J'ai priviliégié l'utilisation de docker car depuis quelques temps, Ecoindex nécessite l'installation et la configuration de playwright. Le docker permet de s'abstraire de toute cette configuration.

Dis moi si ça va ou si tu souhaites faire autre chose ?

**Comment by xadag-yogarik** [comment]
Merci @vvatelot j'utilisais la commande de ton lien déjà, je pensais que avec le nouveau repo ça avait changé donc tout est ok :)
