### ISSUE TITLE
[Bug]: Input file on cli not working on macOS

### ISSUE THREAD

**Issue by jeanremy** [cnumr/EcoIndex_python#83]
### What happened?

When trying to use a csv file as input, I get the following error:

```bash
~/Desktop/test
❯ ls
-rw-r--r--@  1 user  staff  -  25 20 jui 15:22 input.csv

~/Desktop/test
❯ ecoindex-cli analyze --urls-file input.csv
1 validation error for get_urls_from_file
urls_file
  Path does not point to a file [type=path_not_file, input_value='input.csv', input_type=str]
```

I'm on Sonoma 14.3.1, using the latest version of the cli (2.27.1 I think). 
I have tried different paths, like ~/Desktop/test/input.csv, ./input.csv or /Users/user/Desktop/test/input.csv
Am I doing something wrong ?

Thanks !

### Project

Ecoindex CLI

### What OS do you use?

Mac

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Hello @jeanremy, thanks for your issue !
It is not a problem related to what you do, it is the documentation that is not up to date...

If you installed ecoindex-cli following the [documentation](https://github.com/cnumr/ecoindex_python_fullstack/tree/main/projects/ecoindex_cli#quickstart) using docker, the docker container will only have access to the `/tmp/ecoindex-cli` folder of your host, so I guess that if you move your file to `/tmp/ecoindex-cli` and run 
```
ecoindex-cli analyze --urls-file /tmp/ecoindex-cli/input.csv
```
it should work...?

**Comment by jeanremy** [comment]
Thank you for your answer @vvatelot, it works ! 

Should I make a PR to add it to the documentation ?

**Comment by vvatelot** [comment]
Hello @jeanremy if you can do it, I would really appreciate it! 🙂

**Comment by jeanremy** [comment]
Hi @vvatelot,

Done just here : https://github.com/cnumr/ecoindex_python_fullstack/pull/84

I hope it's ok for you !
