### ISSUE TITLE
Question : Licence

### ISSUE THREAD

**Issue by PierreRustOrange** [cnumr/EcoIndex_python#88]
Hi,

I'd like some clarification regarding the open-source licence used for this projet : 
* the CONTRIBUTING file states that all contribution are made under the MIT License, as is all the code of the project :  https://github.com/cnumr/ecoindex_python_fullstack/blob/main/CONTRIBUTING.md#any-contributions-you-make-will-be-under-the-mit-software-license
* but a the same time, the LICENSE file in this project is a "Creative Commons Legal Code - Attribution-NonCommercial-NoDerivs 3.0 Unported" license, which is to my understanding very different (https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en) from the MIT License : 
  * it forbids distributing "modified material", which seems to prevent from forking the code (possibly even just on github to make a pull request ? )
  * It  forbids commercial use, which is allowed by the MIT license

thanks you for all the work on this project ! :)

**Comment by vvatelot** [comment]
Hello @PierreRustOrange thank you very much for this relevant remark!
It is a mistake I made when created the new `ecoindex_fullstack` repository with a wrong copy/paste from [Facebook contributing guide template](https://github.com/facebook/draft-js/blob/a9316a723f9e918afde44dea68b5f9f39b7d9b00/CONTRIBUTING.md)... 

All the projects related to ecoindex are under [Creative commons](https://github.com/cnumr/ecoindex_python_fullstack?tab=License-1-ov-file#readme) license.

I make the change in the contributing guide to avoid confusion, you are right !

**Comment by PierreRustOrange** [comment]
Thanks for your quick reply !

I must confess I'm confused about the implication of the CC BY-NC-ND 4.0 license on code contribution. I'll check that on my side.
